sonar.projectKey=pttswpbe
sonar.projectName=pttswpbe
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=config,controllers,middleware,routes,scripts,services,index.ts
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.mts
sonar.exclusions=node_modules/**,dist/**,coverage/**,uploads/**,research/**,CICD/**,*.xlsx,*.csv,*.json,.env*
