SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE OR ALTER PROCEDURE dbo.MP_InterfaceInfoDataClear
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM dbo.InfoData;
END;
GO

CREATE OR ALTER PROCEDURE dbo.MP_InterfaceHrp1001DboClear
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM dbo.HRP1001;
END;
GO

CREATE OR ALTER PROCEDURE dbo.MP_InterfaceHrp1002DboClear
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM dbo.HRP1002;
END;
GO

CREATE OR ALTER PROCEDURE dbo.MP_InterfaceHrp1001DbOwnerClear
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM db_owner.HRP1001;
END;
GO

CREATE OR ALTER PROCEDURE dbo.MP_InterfaceHrp1002DbOwnerClear
AS
BEGIN
    SET NOCOUNT ON;

    DELETE FROM db_owner.HRP1002;
END;
GO

CREATE OR ALTER PROCEDURE dbo.MP_InterfaceHrpTableColumns
    @TableName nvarchar(128)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        TABLE_SCHEMA,
        COLUMN_NAME,
        ORDINAL_POSITION
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = @TableName
      AND @TableName IN (N'HRP1001', N'HRP1002')
      AND TABLE_SCHEMA IN ('db_owner', 'dbo')
    ORDER BY ORDINAL_POSITION;
END;
GO
